// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualMind.Exchange.Infrastructure.Persistance.Context;

#nullable disable

namespace VirtualMind.Exchange.Infrastructure.Migrations
{
    [DbContext(typeof(ExchangeDbContext))]
    partial class ExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VirtualMind.Exchange.Infrastructure.Entities.CurrencyPurchase", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<double>("AmountInPesos")
                        .HasColumnType("float")
                        .HasColumnName("AMOUNT_IN_PESOS");

                    b.Property<double>("CurrencyExchangeRate")
                        .HasColumnType("float")
                        .HasColumnName("CURRENCY_EXCHANGE_RATE");

                    b.Property<int>("ISOCode")
                        .HasColumnType("int")
                        .HasColumnName("ISO_CODE");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("PURCHASE_DATE");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("CURRENCY_PURCHASE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
